# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20120413221327) do

  create_table "kbodies", :force => true do |t|
    t.integer  "kplan_id"
    t.integer  "nomer_page"
    t.string   "nomer_uroka1"
    t.string   "tema_zaniatia1"
    t.string   "nomer_nedeli1"
    t.integer  "kolvo_chasov1"
    t.string   "vid_zaniatia1"
    t.string   "nagl_posobie1"
    t.string   "zadano1"
    t.string   "samrab_casov1"
    t.string   "samrab_zadanie1"
    t.string   "nomer_uroka2"
    t.string   "tema_zaniatia2"
    t.string   "nomer_nedeli2"
    t.integer  "kolvo_chasov2"
    t.string   "vid_zaniatia2"
    t.string   "nagl_posobie2"
    t.string   "zadano2"
    t.string   "samrab_casov2"
    t.string   "samrab_zadanie2"
    t.string   "nomer_uroka3"
    t.string   "tema_zaniatia3"
    t.string   "nomer_nedeli3"
    t.integer  "kolvo_chasov3"
    t.string   "vid_zaniatia3"
    t.string   "nagl_posobie3"
    t.string   "zadano3"
    t.string   "samrab_casov3"
    t.string   "samrab_zadanie3"
    t.string   "nomer_uroka4"
    t.string   "tema_zaniatia4"
    t.string   "nomer_nedeli4"
    t.integer  "kolvo_chasov4"
    t.string   "vid_zaniatia4"
    t.string   "nagl_posobie4"
    t.string   "zadano4"
    t.string   "samrab_casov4"
    t.string   "samrab_zadanie4"
    t.string   "nomer_uroka5"
    t.string   "tema_zaniatia5"
    t.string   "nomer_nedeli5"
    t.integer  "kolvo_chasov5"
    t.string   "vid_zaniatia5"
    t.string   "nagl_posobie5"
    t.string   "zadano5"
    t.string   "samrab_casov5"
    t.string   "samrab_zadanie5"
    t.string   "nomer_uroka6"
    t.string   "tema_zaniatia6"
    t.string   "nomer_nedeli6"
    t.integer  "kolvo_chasov6"
    t.string   "vid_zaniatia6"
    t.string   "nagl_posobie6"
    t.string   "zadano6"
    t.string   "samrab_casov6"
    t.string   "samrab_zadanie6"
    t.string   "nomer_uroka7"
    t.string   "tema_zaniatia7"
    t.string   "nomer_nedeli7"
    t.integer  "kolvo_chasov7"
    t.string   "vid_zaniatia7"
    t.string   "nagl_posobie7"
    t.string   "zadano7"
    t.string   "samrab_casov7"
    t.string   "samrab_zadanie7"
    t.string   "nomer_uroka8"
    t.string   "tema_zaniatia8"
    t.string   "nomer_nedeli8"
    t.integer  "kolvo_chasov8"
    t.string   "vid_zaniatia8"
    t.string   "nagl_posobie8"
    t.string   "zadano8"
    t.string   "samrab_casov8"
    t.string   "samrab_zadanie8"
    t.string   "nomer_uroka9"
    t.string   "tema_zaniatia9"
    t.string   "nomer_nedeli9"
    t.integer  "kolvo_chasov9"
    t.string   "vid_zaniatia9"
    t.string   "nagl_posobie9"
    t.string   "zadano9"
    t.string   "samrab_casov9"
    t.string   "samrab_zadanie9"
    t.string   "nomer_uroka10"
    t.string   "tema_zaniatia10"
    t.string   "nomer_nedeli10"
    t.integer  "kolvo_chasov10"
    t.string   "vid_zaniatia10"
    t.string   "nagl_posobie10"
    t.string   "zadano10"
    t.string   "samrab_casov10"
    t.string   "samrab_zadanie10"
    t.string   "nomer_uroka11"
    t.string   "tema_zaniatia11"
    t.string   "nomer_nedeli11"
    t.integer  "kolvo_chasov11"
    t.string   "vid_zaniatia11"
    t.string   "nagl_posobie11"
    t.string   "zadano11"
    t.string   "samrab_casov11"
    t.string   "samrab_zadanie11"
    t.string   "nomer_uroka12"
    t.string   "tema_zaniatia12"
    t.string   "nomer_nedeli12"
    t.integer  "kolvo_chasov12"
    t.string   "vid_zaniatia12"
    t.string   "nagl_posobie12"
    t.string   "zadano12"
    t.string   "samrab_casov12"
    t.string   "samrab_zadanie12"
    t.string   "nomer_uroka13"
    t.string   "tema_zaniatia13"
    t.string   "nomer_nedeli13"
    t.integer  "kolvo_chasov13"
    t.string   "vid_zaniatia13"
    t.string   "nagl_posobie13"
    t.string   "zadano13"
    t.string   "samrab_casov13"
    t.string   "samrab_zadanie13"
    t.string   "nomer_uroka14"
    t.string   "tema_zaniatia14"
    t.string   "nomer_nedeli14"
    t.integer  "kolvo_chasov14"
    t.string   "vid_zaniatia14"
    t.string   "nagl_posobie14"
    t.string   "zadano14"
    t.string   "samrab_casov14"
    t.string   "samrab_zadanie14"
    t.string   "nomer_uroka15"
    t.string   "tema_zaniatia15"
    t.string   "nomer_nedeli15"
    t.integer  "kolvo_chasov15"
    t.string   "vid_zaniatia15"
    t.string   "nagl_posobie15"
    t.string   "zadano15"
    t.string   "samrab_casov15"
    t.string   "samrab_zadanie15"
    t.string   "nomer_uroka16"
    t.string   "tema_zaniatia16"
    t.string   "nomer_nedeli16"
    t.integer  "kolvo_chasov16"
    t.string   "vid_zaniatia16"
    t.string   "nagl_posobie16"
    t.string   "zadano16"
    t.string   "samrab_casov16"
    t.string   "samrab_zadanie16"
    t.string   "nomer_uroka17"
    t.string   "tema_zaniatia17"
    t.string   "nomer_nedeli17"
    t.integer  "kolvo_chasov17"
    t.string   "vid_zaniatia17"
    t.string   "nagl_posobie17"
    t.string   "zadano17"
    t.string   "samrab_casov17"
    t.string   "samrab_zadanie17"
    t.string   "nomer_uroka18"
    t.string   "tema_zaniatia18"
    t.string   "nomer_nedeli18"
    t.integer  "kolvo_chasov18"
    t.string   "vid_zaniatia18"
    t.string   "nagl_posobie18"
    t.string   "zadano18"
    t.string   "samrab_casov18"
    t.string   "samrab_zadanie18"
    t.string   "nomer_uroka19"
    t.string   "tema_zaniatia19"
    t.string   "nomer_nedeli19"
    t.integer  "kolvo_chasov19"
    t.string   "vid_zaniatia19"
    t.string   "nagl_posobie19"
    t.string   "zadano19"
    t.string   "samrab_casov19"
    t.string   "samrab_zadanie19"
    t.string   "nomer_uroka20"
    t.string   "tema_zaniatia20"
    t.string   "nomer_nedeli20"
    t.integer  "kolvo_chasov20"
    t.string   "vid_zaniatia20"
    t.string   "nagl_posobie20"
    t.string   "zadano20"
    t.string   "samrab_casov20"
    t.string   "samrab_zadanie20"
    t.string   "nomer_uroka21"
    t.string   "tema_zaniatia21"
    t.string   "nomer_nedeli21"
    t.integer  "kolvo_chasov21"
    t.string   "vid_zaniatia21"
    t.string   "nagl_posobie21"
    t.string   "zadano21"
    t.string   "samrab_casov21"
    t.string   "samrab_zadanie21"
    t.string   "nomer_uroka22"
    t.string   "tema_zaniatia22"
    t.string   "nomer_nedeli22"
    t.integer  "kolvo_chasov22"
    t.string   "vid_zaniatia22"
    t.string   "nagl_posobie22"
    t.string   "zadano22"
    t.string   "samrab_casov22"
    t.string   "samrab_zadanie22"
    t.string   "nomer_uroka23"
    t.string   "tema_zaniatia23"
    t.string   "nomer_nedeli23"
    t.integer  "kolvo_chasov23"
    t.string   "vid_zaniatia23"
    t.string   "nagl_posobie23"
    t.string   "zadano23"
    t.string   "samrab_casov23"
    t.string   "samrab_zadanie23"
    t.string   "nomer_uroka24"
    t.string   "tema_zaniatia24"
    t.string   "nomer_nedeli24"
    t.integer  "kolvo_chasov24"
    t.string   "vid_zaniatia24"
    t.string   "nagl_posobie24"
    t.string   "zadano24"
    t.string   "samrab_casov24"
    t.string   "samrab_zadanie24"
    t.string   "nomer_uroka25"
    t.string   "tema_zaniatia25"
    t.string   "nomer_nedeli25"
    t.integer  "kolvo_chasov25"
    t.string   "vid_zaniatia25"
    t.string   "nagl_posobie25"
    t.string   "zadano25"
    t.string   "samrab_casov25"
    t.string   "samrab_zadanie25"
    t.string   "nomer_uroka26"
    t.string   "tema_zaniatia26"
    t.string   "nomer_nedeli26"
    t.integer  "kolvo_chasov26"
    t.string   "vid_zaniatia26"
    t.string   "nagl_posobie26"
    t.string   "zadano26"
    t.string   "samrab_casov26"
    t.string   "samrab_zadanie26"
    t.datetime "created_at",       :null => false
    t.datetime "updated_at",       :null => false
  end

  create_table "klits", :force => true do |t|
    t.integer  "kplan_id"
    t.string   "literatura1"
    t.string   "literatura2"
    t.string   "literatura3"
    t.string   "literatura4"
    t.string   "literatura5"
    t.string   "literatura6"
    t.string   "literatura7"
    t.string   "literatura8"
    t.string   "literatura9"
    t.string   "literatura10"
    t.string   "literatura11"
    t.string   "literatura12"
    t.string   "literatura13"
    t.string   "literatura14"
    t.string   "literatura15"
    t.string   "literatura16"
    t.string   "literatura17"
    t.string   "literatura18"
    t.string   "literatura19"
    t.string   "literatura20"
    t.string   "literatura21"
    t.string   "literatura22"
    t.string   "literatura23"
    t.string   "literatura24"
    t.datetime "created_at",   :null => false
    t.datetime "updated_at",   :null => false
  end

  create_table "kplans", :force => true do |t|
    t.integer  "user_id"
    t.integer  "predmet_comissia"
    t.datetime "created_at",       :null => false
    t.datetime "updated_at",       :null => false
  end

  create_table "ktitls", :force => true do |t|
    t.integer  "kplan_id"
    t.string   "pregmet"
    t.string   "spec"
    t.string   "group"
    t.string   "kurs"
    t.string   "semestr"
    t.string   "god"
    t.string   "uchregd"
    t.integer  "ch_ned"
    t.integer  "ch_zan"
    t.integer  "ch_labrab"
    t.integer  "ch_kprtk"
    t.integer  "ch_smr"
    t.datetime "created_at", :null => false
    t.datetime "updated_at", :null => false
  end

  create_table "users", :force => true do |t|
    t.string   "nik"
    t.string   "name"
    t.string   "pas"
    t.string   "salt"
    t.integer  "tip"
    t.integer  "predmet_comissia"
    t.datetime "created_at",       :null => false
    t.datetime "updated_at",       :null => false
  end

  add_index "users", ["nik"], :name => "index_users_on_nik", :unique => true

end
